url: https://melaniegershman.github.io
# baseurl: /
repository: melaniegershman/melaniegershman.github.io

# Site settings
title: Melanie Gershman
email: melanie.gershman@gmail.com
description: "Portfolio of work by Melanie Gershman, a full-stack web developer based in New York City, NY."


# Team names, titles and social links
people:

- name: Melanie Gershman
  pic: 3
  position: Full-Stack Developer
  social:
    - title: twitter
      url: http://twitter.com/mel_install
    - title: linkedin
      url: https://www.linkedin.com/in/melaniegershman
    - title: github
      url: http://github.com/melaniegershman

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/mel_install
  - title: instagram
    url: http://instagram.com/ruby_dog.rb
  - title: github
    url: http://github.com/melaniegershman
  - title: linkedin
    url: https://www.linkedin.com/in/melaniegershman

# Postal address (add as many lines as necessary)
address:
  - line: New York, NY

# Build settings
markdown: kramdown
permalink: pretty
